---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: demo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./demo
  prune: true
  sourceRef:
    kind: GitRepository
    name: demo
  validation: client
